// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ContextList() {
  return window['go']['controllers']['Kube']['ContextList']();
}

export function NamespaceList(arg1) {
  return window['go']['controllers']['Kube']['NamespaceList'](arg1);
}

export function OnStartup(arg1) {
  return window['go']['controllers']['Kube']['OnStartup'](arg1);
}
