// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function ContextList():Promise<Array<string>>;

export function NamespaceList(arg1:string):Promise<Array<string>>;

export function OnStartup(arg1:context.Context):void;
