// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {context} from '../models';

export function Command(arg1:string,arg2:string,arg3:string,arg4:string):Promise<app.CommandResult>;

export function ContextList():Promise<Array<string>>;

export function Describe(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function NamespaceList(arg1:string):Promise<Array<string>>;

export function OnStartup(arg1:context.Context):Promise<void>;

export function ResourceList(arg1:string,arg2:string,arg3:string):Promise<Array<app.ResourceTable>>;

export function Yaml(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;
