// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Command(arg1, arg2, arg3, arg4) {
  return window['go']['main']['Kube']['Command'](arg1, arg2, arg3, arg4);
}

export function ContextList() {
  return window['go']['main']['Kube']['ContextList']();
}

export function Describe(arg1, arg2, arg3, arg4) {
  return window['go']['main']['Kube']['Describe'](arg1, arg2, arg3, arg4);
}

export function NamespaceList(arg1) {
  return window['go']['main']['Kube']['NamespaceList'](arg1);
}

export function OnStartup(arg1) {
  return window['go']['main']['Kube']['OnStartup'](arg1);
}

export function ResourceList(arg1, arg2, arg3) {
  return window['go']['main']['Kube']['ResourceList'](arg1, arg2, arg3);
}

export function Yaml(arg1, arg2, arg3, arg4) {
  return window['go']['main']['Kube']['Yaml'](arg1, arg2, arg3, arg4);
}
